### ISSUE TITLE
The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

### ISSUE THREAD

**Issue by laxman1983** [OfficeDev/microsoft-teams-apps-employeeideas#1]
Getting below error while import solution. do you have any idea to resolve this error 

![image](https://user-images.githubusercontent.com/18114594/104015555-14831f00-51b5-11eb-8ba6-0191a02d7808.png)

**Comment by Naveen2514** [comment]
We are not able to open the app in PowerApps, getting above error.

**Comment by wfiles6975** [comment]
I am getting the same error: The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

**Comment by nichalm** [comment]
Hello Team. I am also getting the same error. Any idea how this issue can be resolved. It would be great if we could get the solution files and deploy.

**Comment by Dev-Mom** [comment]
Ditto...

**Comment by navjotm** [comment]
Updated installation instructions to address this issue.

**Comment by navjotm** [comment]
Refer to updated [instructions](https://github.com/OfficeDev/microsoft-teams-apps-employeeideas/tree/main/Installation%20Instructions).

**Comment by C-A-BIRD** [comment]
404 link for updated instructions.
